"use client";

import { App, Button, Drawer, Form, Input, Popconfirm, Space, Switch, Table, Tag } from "antd";
import type { ColumnsType } from "antd/es/table";
import { PencilIcon, PlusIcon, Trash2Icon } from "lucide-react";
import { useEffect, useState } from "react";
import type { AssistantResource, ResourceKind } from "@/lib/assistant-resources";
import { AdminHeader } from "./admin-shell";

type ResourceForm = { name: string; description: string; enabled: boolean; content: string; endpoint: string };
const labels: Record<ResourceKind, { title: string; description: string; contentLabel: string; contentPlaceholder: string }> = {
  agent: { title: "助手", description: "维护可在聊天中通过 @ 选择的助手和系统 Prompt。", contentLabel: "系统 Prompt", contentPlaceholder: "定义助手的角色、目标和回答规则" },
  knowledge: { title: "知识库", description: "维护知识库说明和资料内容，后续可接入文档解析与向量检索。", contentLabel: "资料内容", contentPlaceholder: "输入知识库资料或维护说明" },
  tool: { title: "工具", description: "维护可在聊天中引用的工具定义、参数和执行端点。", contentLabel: "参数 JSON", contentPlaceholder: '{\n  "query": { "type": "string", "description": "搜索关键词" }\n}' },
};

export function ResourcesClient({ kind, currentUsername, avatarUrl }: { kind: ResourceKind; currentUsername: string; avatarUrl?: string }) {
  const { message } = App.useApp();
  const meta = labels[kind];
  const [resources, setResources] = useState<AssistantResource[]>([]); const [form, setForm] = useState<ResourceForm>({ name: "", description: "", enabled: true, content: "", endpoint: "" }); const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  useEffect(() => { let active = true; void fetch("/api/assistant-resources").then(async (response) => ({ response, result: await response.json().catch(() => null) as { resources?: AssistantResource[]; error?: string } | null })).then(({ response, result }) => { if (!active) return; if (!response.ok) return setError(result?.error ?? "加载失败"); setResources((result?.resources ?? []).filter((item) => item.kind === kind)); }); return () => { active = false; }; }, [kind]);
  function close() { setOpen(false); setEditingId(null); setForm({ name: "", description: "", enabled: true, content: "", endpoint: "" }); }
  function edit(resource?: AssistantResource) { setError(""); setEditingId(resource?.id ?? null); const config = resource?.config ?? {}; setForm(resource ? { name: resource.name, description: resource.description, enabled: resource.enabled, content: kind === "agent" ? String(config.prompt ?? "") : kind === "knowledge" ? String(config.content ?? "") : JSON.stringify(config.parameters ?? {}, null, 2), endpoint: String(config.endpoint ?? "") } : { name: "", description: "", enabled: true, content: "", endpoint: "" }); setOpen(true); }
  async function save() { setError(""); let config: Record<string, unknown> = {}; if (kind === "agent") config = { prompt: form.content }; else if (kind === "knowledge") config = { content: form.content }; else { try { config = { parameters: JSON.parse(form.content || "{}"), endpoint: form.endpoint }; } catch { return setError("参数 JSON 格式不正确"); } } const body = { kind, name: form.name, description: form.description, enabled: form.enabled, config }; const response = await fetch("/api/assistant-resources", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editingId ? { id: editingId, ...body } : body) }); const result = await response.json().catch(() => null) as { resource?: AssistantResource; error?: string } | null; if (!response.ok) return setError(result?.error ?? "保存失败"); if (result?.resource) setResources((current) => editingId ? current.map((item) => item.id === editingId ? result.resource! : item) : [...current, result.resource!]); message.success(editingId ? "资源已更新" : "资源已创建"); close(); }
  async function remove(resource: AssistantResource) { const response = await fetch("/api/assistant-resources", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: resource.id }) }); const result = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) return setError(result?.error ?? "删除失败"); setResources((current) => current.filter((item) => item.id !== resource.id)); message.success("资源已删除"); }
  async function toggle(resource: AssistantResource) { const response = await fetch("/api/assistant-resources", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: resource.id, enabled: !resource.enabled }) }); const result = await response.json().catch(() => null) as { resource?: AssistantResource; error?: string } | null; if (!response.ok) return setError(result?.error ?? "更新失败"); if (result?.resource) setResources((current) => current.map((item) => item.id === resource.id ? result.resource! : item)); }
  const columns: ColumnsType<AssistantResource> = [{ title: "名称", dataIndex: "name", key: "name", render: (value: string, resource) => <Space direction="vertical" size={0}><strong>{value}</strong><small className="admin-secondary-text">{resource.id}</small></Space> }, { title: "描述", dataIndex: "description", key: "description", ellipsis: true }, { title: "状态", key: "enabled", width: 110, render: (_, resource) => <Button type="link" size="small" onClick={(event) => { event.stopPropagation(); void toggle(resource); }}>{resource.enabled ? <Tag color="green">已启用</Tag> : <Tag>已停用</Tag>}</Button> }, { title: "更新时间", dataIndex: "updatedAt", key: "updatedAt", width: 170, render: (value: string) => new Date(value).toLocaleString("zh-CN") }, { title: "操作", key: "actions", width: 110, render: (_, resource) => <Space onClick={(event) => event.stopPropagation()}><Button type="text" size="small" icon={<PencilIcon className="size-3.5" />} onClick={() => edit(resource)} /><Popconfirm title={`确定删除${meta.title}“${resource.name}”？`} onConfirm={() => void remove(resource)}><Button type="text" danger size="small" icon={<Trash2Icon className="size-3.5" />} /></Popconfirm></Space> }];
  return <div className="admin-page"><AdminHeader menuTitle={meta.title} currentUsername={currentUsername} avatarUrl={avatarUrl} /><section className="admin-content"><nav className="breadcrumb" aria-label="面包屑导航"><span>系统管理</span><span>/</span><strong>{meta.title}</strong></nav><div className="admin-toolbar"><p className="admin-description">{meta.description}</p><Button type="primary" icon={<PlusIcon className="size-4" />} onClick={() => edit()}>新增{meta.title}</Button></div>{error && <div className="form-error" role="alert">{error}</div>}<Table<AssistantResource> rowKey="id" columns={columns} dataSource={resources} scroll={{ x: 760 }} pagination={{ pageSize: 10, showSizeChanger: false, showTotal: (total) => `共 ${total} 个${meta.title}` }} onRow={(resource) => ({ onClick: () => edit(resource), className: "clickable-row" })} /><Drawer title={editingId ? `编辑${meta.title}` : `新增${meta.title}`} open={open} onClose={close} width="clamp(28rem, 42vw, 42rem)" destroyOnHidden footer={<Space style={{ width: "100%", justifyContent: "flex-end" }}><Button onClick={close}>取消</Button><Button type="primary" onClick={() => void save()}>保存{meta.title}</Button></Space>}><Form layout="vertical"><Form.Item label="名称" required><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Form.Item><Form.Item label="描述"><Input.TextArea rows={2} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Form.Item><Form.Item label={meta.contentLabel}><Input.TextArea rows={kind === "knowledge" ? 12 : 8} placeholder={meta.contentPlaceholder} value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} /></Form.Item>{kind === "tool" && <Form.Item label="执行端点"><Input placeholder="可选，例如 https://..." value={form.endpoint} onChange={(event) => setForm({ ...form, endpoint: event.target.value })} /></Form.Item>}<Form.Item label="启用状态"><Switch checked={form.enabled} onChange={(enabled) => setForm({ ...form, enabled })} /></Form.Item></Form></Drawer></section></div>;
}
