import { getCurrentUser } from "@/lib/auth";
import { createAssistantResource, deleteAssistantResource, listAssistantResources, updateAssistantResource, type ResourceKind } from "@/lib/assistant-resources";
import { NextResponse } from "next/server";

async function requireAdmin() { const user = await getCurrentUser(); return user?.role === "admin"; }

export async function GET() { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "请先登录" }, { status: 401 }); try { return NextResponse.json({ resources: await listAssistantResources({ enabledOnly: user.role !== "admin" }) }); } catch (error) { console.error("List assistant resources error", error); return NextResponse.json({ error: "加载资源失败" }, { status: 503 }); } }
export async function POST(request: Request) { if (!(await requireAdmin())) return NextResponse.json({ error: "无权操作" }, { status: 403 }); try { const body = await request.json() as { kind?: ResourceKind; name?: string; description?: string; enabled?: boolean; config?: Record<string, unknown> }; if (!body.kind || !body.name) return NextResponse.json({ error: "类型和名称不能为空" }, { status: 400 }); return NextResponse.json({ resource: await createAssistantResource({ kind: body.kind, name: body.name, description: body.description, enabled: body.enabled, config: body.config }) }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "创建资源失败" }, { status: 400 }); } }
export async function PATCH(request: Request) { if (!(await requireAdmin())) return NextResponse.json({ error: "无权操作" }, { status: 403 }); try { const body = await request.json() as { id?: string; kind?: ResourceKind; name?: string; description?: string; enabled?: boolean; config?: Record<string, unknown> }; if (!body.id) return NextResponse.json({ error: "缺少资源 ID" }, { status: 400 }); const resource = await updateAssistantResource(body.id, body); if (!resource) return NextResponse.json({ error: "资源不存在" }, { status: 404 }); return NextResponse.json({ resource }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "更新资源失败" }, { status: 400 }); } }
export async function DELETE(request: Request) { if (!(await requireAdmin())) return NextResponse.json({ error: "无权操作" }, { status: 403 }); try { const { id } = await request.json() as { id?: string }; if (!id) return NextResponse.json({ error: "缺少资源 ID" }, { status: 400 }); if (!(await deleteAssistantResource(id))) return NextResponse.json({ error: "资源不存在" }, { status: 404 }); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "删除资源失败" }, { status: 400 }); } }
